server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql:///wechat_mall?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    # 连接池配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #连接等待超时时间
    maxWait: 60000
    #配置隔多久进行一次检测(检测可以关闭的空闲连接)
    timeBetweenEvictionRunsMillis: 60000
    #配置连接在池中的最小生存时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  # redis配置
  redis:
    host: 112.74.164.219
    port: 6379
    database: 0
    password: tGgdXfLFQvEquUF6djKePpB1leBg8ca0


mybatis:
  mapper-locations: classpath:mapper/*.xml

#分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

druid:
  manager:
    username: admin
    pwd: liuxu123

wechat-request-token: SnGW5ZkjKeYrbdlHQcwoIuF6xmiLCT

wechat:
  miniapp:
    appid: wx53564d8cbb2933d8
    secret: 7ea58ad28ee995abef577969eee9addb
    token: tFXxidXLTUr18BFD0LT3
    aesKey: kO6R8NhRDasa4ysoyNU5xCPoMLPxfh4ELf7Lqha8GZr
    msgDataFormat: JSON

LOGIN:
  SESSION_KEY_PRE: LOGIN_KEY

# 订单起送价格    业务逻辑:如果订单小于N元就添加1元的运费,如果大于等于N元就没有运费
starting_price: 7